#!/usr/bin/env ruby

require_relative "lib/setup"
require "slop"
require "bulk_replace"

def get_options
  options = Slop::Options.new do |o|
    o.on "-h", "--help", "print this usage information" do
      puts o
      exit
    end
    o.string "--github-token", "GitHub API token"

    o.separator ""
    o.string "--file-path", "path to the file to update (required)", required: true
    o.string "--old-content", "content to be changed (required)", required: true
    o.string "--new-content", "new content (required)", required: true
    o.boolean "--global", "replace all occurrences of content (required)", required: true

    o.separator "\npull request options:"
    o.string "--branch", "name of the branch to commit the change to (required)", required: true
    o.string "--commit-title", "title for the commit (required)", required: true
    o.string "--commit-description", "description of the commit (required)", required: true
    o.string "--pr-title", "title for the PR to raise (optional)", required: false
    o.string "--pr-description", "description of the PR to raise (optional)", required: false
    o.boolean "--use-regex", "use a regex pattern to find content (optional)", required: false, default: false
    o.boolean "--continue-on-existing-branch", "automatically confirm all 'Continue on existing branch?' questions", required: false, default: false
    o.boolean "--file-path-is-regex", "use a regex pattern to find file paths (optional)", required: false, default: false
  end

  begin
    options.parse(ARGV).to_hash
  rescue Slop::Error => e
    puts e
    puts options
    exit
  end
end

bulk_replace(**get_options)
